# Generated by Django 5.2.7 on 2025-10-08 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('compras', 'Compras'), ('devolucion', 'Devolución')], max_length=100, verbose_name='Nombres')),
            ],
            options={
                'verbose_name': 'TiposEntradas',
            },
        ),
    ]
