# Generated by Django 5.2.7 on 2025-10-08 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pais',
            field=models.IntegerField(choices=[(1, 'Nicaragua'), (2, 'Costa Rica'), (3, 'Honduras'), (4, 'Panamá')], default=1),
        ),
    ]
