# Generated by Django 5.2.7 on 2025-10-08 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0002_user_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pais',
            field=models.IntegerField(choices=[(1, 'Nicaragua'), (2, 'Honduras'), (3, 'Costa Rica'), (4, 'Panamá')], default=1),
        ),
    ]
