# Generated by Django 5.2.7 on 2025-10-08 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SucursalPan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Panama', editable=False, max_length=255)),
                ('codigo', models.IntegerField(default=4, editable=False)),
            ],
            options={
                'verbose_name': 'SucursalPan',
            },
        ),
    ]
