# Generated by Django 5.2.7 on 2025-10-08 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Categorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibrosPan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('costoactual', models.BigIntegerField(blank=True, null=True, verbose_name='CostoActual')),
                ('existencia', models.BigIntegerField(blank=True, null=True, verbose_name='Existencia')),
                ('categorias', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Categorias.categoria', verbose_name='Categorias')),
            ],
            options={
                'verbose_name': 'LibrosPan',
            },
        ),
    ]
