# Generated by Django 5.2.7 on 2025-10-08 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CostaRica', '__first__'),
        ('Hondura', '__first__'),
        ('Libros', '__first__'),
        ('LibrosCos', '__first__'),
        ('LibrosHon', '__first__'),
        ('LibrosPan', '__first__'),
        ('Nicaragua', '__first__'),
        ('Panama', '__first__'),
        ('TipoSalida', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalidaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'SalidasDetalles',
            },
        ),
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechasalida', models.CharField(max_length=100, verbose_name='FechaSalida')),
                ('sucursalid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Nicaragua.sucursal', verbose_name='Sucursal')),
                ('sucursalidcos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='CostaRica.sucursalcos', verbose_name='Sucursalcos')),
                ('sucursalidhon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Hondura.sucursalhon', verbose_name='SucursalHon')),
                ('sucursalidpan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Panama.sucursalpan', verbose_name='SucursalPan')),
                ('tiposalida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='TipoSalida.tiposalida', verbose_name='TipoSalida')),
            ],
            options={
                'verbose_name': 'Salidas',
            },
        ),
        migrations.CreateModel(
            name='DetalleSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costosalida', models.BigIntegerField(blank=True, null=True, verbose_name='CostoSalida')),
                ('cantidad', models.BigIntegerField(blank=True, null=True, verbose_name='Cantidad')),
                ('libro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Libros.libro', verbose_name='Libro')),
                ('librocos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='LibrosCos.libroscos', verbose_name='LibroCos')),
                ('librohon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='LibrosHon.libroshon', verbose_name='LibroHon')),
                ('libropan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='LibrosPan.librospan', verbose_name='LibroPan')),
                ('salida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Salida.salida', verbose_name='Salida')),
            ],
            options={
                'verbose_name': 'DetallesSalidas',
            },
        ),
    ]
